-- Copyright (C) 2023  Intel Corporation. All rights reserved.
-- Your use of Intel Corporation's design tools, logic functions 
-- and other software and tools, and any partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Intel Program License 
-- Subscription Agreement, the Intel Quartus Prime License Agreement,
-- the Intel FPGA IP License Agreement, or other applicable license
-- agreement, including, without limitation, that your use is for
-- the sole purpose of programming logic devices manufactured by
-- Intel and sold by Intel or its authorized distributors.  Please
-- refer to the applicable agreement for further details, at
-- https://fpgasoftware.intel.com/eula.

-- PROGRAM		"Quartus Prime"
-- VERSION		"Version 23.1std.0 Build 991 11/28/2023 SC Lite Edition"
-- CREATED		"Tue Jun 23 20:49:22 2026"

LIBRARY ieee;
USE ieee.std_logic_1164.all; 

LIBRARY work;

ENTITY scpmod IS 
	PORT
	(
		CLK :  IN  STD_LOGIC;
		SYSRST :  IN  STD_LOGIC;
		CLR :  IN  STD_LOGIC_VECTOR(2 DOWNTO 0);
		SLIDERS :  IN  STD_LOGIC_VECTOR(9 DOWNTO 0);
		A3SEL :  OUT  STD_LOGIC;
		ROTSEL :  OUT  STD_LOGIC;
		SHAMTSEL :  OUT  STD_LOGIC;
		SRC2SEL :  OUT  STD_LOGIC;
		REGWR :  OUT  STD_LOGIC;
		MEMWR :  OUT  STD_LOGIC;
		MEMRD :  OUT  STD_LOGIC;
		A4SEL :  OUT  STD_LOGIC;
		C :  OUT  STD_LOGIC;
		V :  OUT  STD_LOGIC;
		N :  OUT  STD_LOGIC;
		Z :  OUT  STD_LOGIC;
		ALUF :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		ALUSEL :  OUT  STD_LOGIC_VECTOR(3 DOWNTO 0);
		BRADDR :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		CPSRWR :  OUT  STD_LOGIC_VECTOR(1 DOWNTO 0);
		IBUS :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		LEDS :  OUT  STD_LOGIC_VECTOR(9 DOWNTO 0);
		MOTORS :  OUT  STD_LOGIC_VECTOR(4 DOWNTO 0);
		PC4 :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		PCSEL :  OUT  STD_LOGIC_VECTOR(1 DOWNTO 0);
		SEG0 :  OUT  STD_LOGIC_VECTOR(7 DOWNTO 0);
		SEG1 :  OUT  STD_LOGIC_VECTOR(7 DOWNTO 0);
		SEG2 :  OUT  STD_LOGIC_VECTOR(7 DOWNTO 0);
		SEG3 :  OUT  STD_LOGIC_VECTOR(7 DOWNTO 0);
		SEG4 :  OUT  STD_LOGIC_VECTOR(7 DOWNTO 0);
		SEG5 :  OUT  STD_LOGIC_VECTOR(7 DOWNTO 0);
		SRC1 :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		SRC2 :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		WD4 :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		WD4SEL :  OUT  STD_LOGIC_VECTOR(1 DOWNTO 0)
	);
END scpmod;

ARCHITECTURE bdf_type OF scpmod IS 

COMPONENT addressdecoder
	PORT(MEMRD : IN STD_LOGIC;
		 MEMWR : IN STD_LOGIC;
		 ADDR : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 LD3 : OUT STD_LOGIC;
		 LD2 : OUT STD_LOGIC;
		 LD1 : OUT STD_LOGIC;
		 LD0 : OUT STD_LOGIC;
		 DATASEL : OUT STD_LOGIC_VECTOR(1 DOWNTO 0)
	);
END COMPONENT;

COMPONENT dmem
	PORT(MEMWR : IN STD_LOGIC;
		 RST : IN STD_LOGIC;
		 CLK : IN STD_LOGIC;
		 A : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 WD : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 RD : OUT STD_LOGIC_VECTOR(31 DOWNTO 0)
	);
END COMPONENT;

COMPONENT synchronizer
	PORT(SYSRST : IN STD_LOGIC;
		 CLK : IN STD_LOGIC;
		 RST : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT seg7decode
	PORT(A : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 SEG0 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
		 SEG1 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
		 SEG2 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
		 SEG3 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
		 SEG4 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
		 SEG5 : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
	);
END COMPONENT;

COMPONENT busmux4to1
	PORT(D0 : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 D1 : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 D2 : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 D3 : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 S : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
		 Y : OUT STD_LOGIC_VECTOR(31 DOWNTO 0)
	);
END COMPONENT;

COMPONENT scp
	PORT(RST : IN STD_LOGIC;
		 CLK : IN STD_LOGIC;
		 MEMDATAIN : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 A3SEL : OUT STD_LOGIC;
		 ROTSEL : OUT STD_LOGIC;
		 SHAMTSEL : OUT STD_LOGIC;
		 SRC2SEL : OUT STD_LOGIC;
		 REGWR : OUT STD_LOGIC;
		 MEMWR : OUT STD_LOGIC;
		 MEMRD : OUT STD_LOGIC;
		 A4SEL : OUT STD_LOGIC;
		 C : OUT STD_LOGIC;
		 V : OUT STD_LOGIC;
		 N : OUT STD_LOGIC;
		 Z : OUT STD_LOGIC;
		 ALUF : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
		 ALUSEL : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
		 BRADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
		 CPSRWR : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
		 IBUS : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
		 MEMADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
		 MEMDATAOUT : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
		 PC4 : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
		 PCSEL : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
		 SRC1 : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
		 SRC2 : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
		 WD4 : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
		 WD4SEL : OUT STD_LOGIC_VECTOR(1 DOWNTO 0)
	);
END COMPONENT;

COMPONENT regn
GENERIC (WIDTH : INTEGER
			);
	PORT(LD : IN STD_LOGIC;
		 RST : IN STD_LOGIC;
		 CLK : IN STD_LOGIC;
		 D : IN STD_LOGIC_VECTOR(9 DOWNTO 0);
		 Q : OUT STD_LOGIC_VECTOR(9 DOWNTO 0)
	);
END COMPONENT;

SIGNAL	CLR10 :  STD_LOGIC;
SIGNAL	CLR11 :  STD_LOGIC;
SIGNAL	CLR12 :  STD_LOGIC;
SIGNAL	CLR13 :  STD_LOGIC;
SIGNAL	CLR14 :  STD_LOGIC;
SIGNAL	CLR15 :  STD_LOGIC;
SIGNAL	CLR16 :  STD_LOGIC;
SIGNAL	CLR17 :  STD_LOGIC;
SIGNAL	CLR18 :  STD_LOGIC;
SIGNAL	CLR19 :  STD_LOGIC;
SIGNAL	CLR20 :  STD_LOGIC;
SIGNAL	CLR21 :  STD_LOGIC;
SIGNAL	CLR22 :  STD_LOGIC;
SIGNAL	CLR23 :  STD_LOGIC;
SIGNAL	CLR24 :  STD_LOGIC;
SIGNAL	CLR25 :  STD_LOGIC;
SIGNAL	CLR26 :  STD_LOGIC;
SIGNAL	CLR27 :  STD_LOGIC;
SIGNAL	CLR28 :  STD_LOGIC;
SIGNAL	CLR29 :  STD_LOGIC;
SIGNAL	CLR3 :  STD_LOGIC;
SIGNAL	CLR30 :  STD_LOGIC;
SIGNAL	CLR31 :  STD_LOGIC;
SIGNAL	CLR4 :  STD_LOGIC;
SIGNAL	CLR5 :  STD_LOGIC;
SIGNAL	CLR6 :  STD_LOGIC;
SIGNAL	CLR7 :  STD_LOGIC;
SIGNAL	CLR8 :  STD_LOGIC;
SIGNAL	CLR9 :  STD_LOGIC;
SIGNAL	DATASEL :  STD_LOGIC_VECTOR(1 DOWNTO 0);
SIGNAL	LD0 :  STD_LOGIC;
SIGNAL	LD1 :  STD_LOGIC;
SIGNAL	LD2 :  STD_LOGIC;
SIGNAL	LD3 :  STD_LOGIC;
SIGNAL	MEMADDR :  STD_LOGIC_VECTOR(31 DOWNTO 0);
SIGNAL	MEMDATA :  STD_LOGIC_VECTOR(31 DOWNTO 0);
SIGNAL	MEMDATAOUT :  STD_LOGIC_VECTOR(31 DOWNTO 0);
SIGNAL	MEMRD_ALTERA_SYNTHESIZED :  STD_LOGIC;
SIGNAL	MEMWR_ALTERA_SYNTHESIZED :  STD_LOGIC;
SIGNAL	RST :  STD_LOGIC;
SIGNAL	SLIDERS10 :  STD_LOGIC;
SIGNAL	SLIDERS11 :  STD_LOGIC;
SIGNAL	SLIDERS12 :  STD_LOGIC;
SIGNAL	SLIDERS13 :  STD_LOGIC;
SIGNAL	SLIDERS14 :  STD_LOGIC;
SIGNAL	SLIDERS15 :  STD_LOGIC;
SIGNAL	SLIDERS16 :  STD_LOGIC;
SIGNAL	SLIDERS17 :  STD_LOGIC;
SIGNAL	SLIDERS18 :  STD_LOGIC;
SIGNAL	SLIDERS19 :  STD_LOGIC;
SIGNAL	SLIDERS20 :  STD_LOGIC;
SIGNAL	SLIDERS21 :  STD_LOGIC;
SIGNAL	SLIDERS22 :  STD_LOGIC;
SIGNAL	SLIDERS23 :  STD_LOGIC;
SIGNAL	SLIDERS24 :  STD_LOGIC;
SIGNAL	SLIDERS25 :  STD_LOGIC;
SIGNAL	SLIDERS26 :  STD_LOGIC;
SIGNAL	SLIDERS27 :  STD_LOGIC;
SIGNAL	SLIDERS28 :  STD_LOGIC;
SIGNAL	SLIDERS29 :  STD_LOGIC;
SIGNAL	SLIDERS30 :  STD_LOGIC;
SIGNAL	SLIDERS31 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_0 :  STD_LOGIC_VECTOR(31 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_1 :  STD_LOGIC_VECTOR(0 TO 31);
SIGNAL	SYNTHESIZED_WIRE_2 :  STD_LOGIC_VECTOR(31 DOWNTO 0);

SIGNAL	GDFX_TEMP_SIGNAL_1 :  STD_LOGIC_VECTOR(31 DOWNTO 0);
SIGNAL	GDFX_TEMP_SIGNAL_0 :  STD_LOGIC_VECTOR(31 DOWNTO 0);

BEGIN 
SYNTHESIZED_WIRE_1 <= "00000000000000000000000000000000";

GDFX_TEMP_SIGNAL_1 <= (SLIDERS31 & SLIDERS30 & SLIDERS29 & SLIDERS28 & SLIDERS27 & SLIDERS26 & SLIDERS25 & SLIDERS24 & SLIDERS23 & SLIDERS22 & SLIDERS21 & SLIDERS20 & SLIDERS19 & SLIDERS18 & SLIDERS17 & SLIDERS16 & SLIDERS15 & SLIDERS14 & SLIDERS13 & SLIDERS12 & SLIDERS11 & SLIDERS10 & SLIDERS(9) & SLIDERS(8) & SLIDERS(7) & SLIDERS(6) & SLIDERS(5) & SLIDERS(4) & SLIDERS(3) & SLIDERS(2) & SLIDERS(1) & SLIDERS(0));
GDFX_TEMP_SIGNAL_0 <= (CLR31 & CLR30 & CLR29 & CLR28 & CLR27 & CLR26 & CLR25 & CLR24 & CLR23 & CLR22 & CLR21 & CLR20 & CLR19 & CLR18 & CLR17 & CLR16 & CLR15 & CLR14 & CLR13 & CLR12 & CLR11 & CLR10 & CLR9 & CLR8 & CLR7 & CLR6 & CLR5 & CLR4 & CLR3 & CLR(2) & CLR(1) & CLR(0));


b2v_ADDRESS_DECODER : addressdecoder
PORT MAP(MEMRD => MEMRD_ALTERA_SYNTHESIZED,
		 MEMWR => MEMWR_ALTERA_SYNTHESIZED,
		 ADDR => MEMADDR,
		 LD3 => LD3,
		 LD2 => LD2,
		 LD1 => LD1,
		 LD0 => LD0,
		 DATASEL => DATASEL);


b2v_DATA_MEMORY : dmem
PORT MAP(MEMWR => LD3,
		 RST => RST,
		 CLK => CLK,
		 A => MEMADDR,
		 WD => MEMDATAOUT,
		 RD => SYNTHESIZED_WIRE_2);


b2v_inst : synchronizer
PORT MAP(SYSRST => SYSRST,
		 CLK => CLK,
		 RST => RST);



b2v_inst11 : seg7decode
PORT MAP(A => SYNTHESIZED_WIRE_0,
		 SEG0 => SEG0,
		 SEG1 => SEG1,
		 SEG2 => SEG2,
		 SEG3 => SEG3,
		 SEG4 => SEG4,
		 SEG5 => SEG5);



b2v_inst3 : busmux4to1
PORT MAP(D0 => SYNTHESIZED_WIRE_1,
		 D1 => GDFX_TEMP_SIGNAL_0,
		 D2 => GDFX_TEMP_SIGNAL_1,
		 D3 => SYNTHESIZED_WIRE_2,
		 S => DATASEL,
		 Y => MEMDATA);



b2v_inst5 : scp
PORT MAP(RST => RST,
		 CLK => CLK,
		 MEMDATAIN => MEMDATA,
		 A3SEL => A3SEL,
		 ROTSEL => ROTSEL,
		 SHAMTSEL => SHAMTSEL,
		 SRC2SEL => SRC2SEL,
		 REGWR => REGWR,
		 MEMWR => MEMWR_ALTERA_SYNTHESIZED,
		 MEMRD => MEMRD_ALTERA_SYNTHESIZED,
		 A4SEL => A4SEL,
		 C => C,
		 V => V,
		 N => N,
		 Z => Z,
		 ALUF => ALUF,
		 ALUSEL => ALUSEL,
		 BRADDR => BRADDR,
		 CPSRWR => CPSRWR,
		 IBUS => IBUS,
		 MEMADDR => MEMADDR,
		 MEMDATAOUT => MEMDATAOUT,
		 PC4 => PC4,
		 PCSEL => PCSEL,
		 SRC1 => SRC1,
		 SRC2 => SRC2,
		 WD4 => WD4,
		 WD4SEL => WD4SEL);


b2v_LED_REGISTER : regn
GENERIC MAP(WIDTH => 10
			)
PORT MAP(LD => LD0,
		 RST => RST,
		 CLK => CLK,
		 D => MEMDATAOUT(9 DOWNTO 0),
		 Q => LEDS);


b2v_MOTORS_REGISTER : regn
GENERIC MAP(WIDTH => 5
			)
PORT MAP(LD => LD1,
		 RST => RST,
		 CLK => CLK,
		 D => MEMDATAOUT(4 DOWNTO 0),
		 Q => MOTORS);


b2v_SEG7_REGISTER : regn
GENERIC MAP(WIDTH => 32
			)
PORT MAP(LD => LD2,
		 RST => RST,
		 CLK => CLK,
		 D => MEMDATAOUT,
		 Q => SYNTHESIZED_WIRE_0);

MEMWR <= MEMWR_ALTERA_SYNTHESIZED;
MEMRD <= MEMRD_ALTERA_SYNTHESIZED;

END bdf_type;