-- Copyright (C) 2023  Intel Corporation. All rights reserved.
-- Your use of Intel Corporation's design tools, logic functions 
-- and other software and tools, and any partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Intel Program License 
-- Subscription Agreement, the Intel Quartus Prime License Agreement,
-- the Intel FPGA IP License Agreement, or other applicable license
-- agreement, including, without limitation, that your use is for
-- the sole purpose of programming logic devices manufactured by
-- Intel and sold by Intel or its authorized distributors.  Please
-- refer to the applicable agreement for further details, at
-- https://fpgasoftware.intel.com/eula.

-- PROGRAM		"Quartus Prime"
-- VERSION		"Version 23.1std.0 Build 991 11/28/2023 SC Lite Edition"
-- CREATED		"Tue Jun 23 20:48:54 2026"

LIBRARY ieee;
USE ieee.std_logic_1164.all; 

LIBRARY work;

ENTITY scp IS 
	PORT
	(
		RST :  IN  STD_LOGIC;
		CLK :  IN  STD_LOGIC;
		MEMDATAIN :  IN  STD_LOGIC_VECTOR(31 DOWNTO 0);
		A3SEL :  OUT  STD_LOGIC;
		ROTSEL :  OUT  STD_LOGIC;
		SHAMTSEL :  OUT  STD_LOGIC;
		SRC2SEL :  OUT  STD_LOGIC;
		REGWR :  OUT  STD_LOGIC;
		MEMWR :  OUT  STD_LOGIC;
		MEMRD :  OUT  STD_LOGIC;
		A4SEL :  OUT  STD_LOGIC;
		C :  OUT  STD_LOGIC;
		V :  OUT  STD_LOGIC;
		N :  OUT  STD_LOGIC;
		Z :  OUT  STD_LOGIC;
		ALUF :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		ALUSEL :  OUT  STD_LOGIC_VECTOR(3 DOWNTO 0);
		BRADDR :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		CPSRWR :  OUT  STD_LOGIC_VECTOR(1 DOWNTO 0);
		IBUS :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		MEMADDR :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		MEMDATAOUT :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		PC4 :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		PCSEL :  OUT  STD_LOGIC_VECTOR(1 DOWNTO 0);
		SRC1 :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		SRC2 :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		WD4 :  OUT  STD_LOGIC_VECTOR(31 DOWNTO 0);
		WD4SEL :  OUT  STD_LOGIC_VECTOR(1 DOWNTO 0)
	);
END scp;

ARCHITECTURE bdf_type OF scp IS 

COMPONENT busmux4to1
	PORT(D0 : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 D1 : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 D2 : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 D3 : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 S : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
		 Y : OUT STD_LOGIC_VECTOR(31 DOWNTO 0)
	);
END COMPONENT;

COMPONENT control
	PORT(C : IN STD_LOGIC;
		 V : IN STD_LOGIC;
		 N : IN STD_LOGIC;
		 Z : IN STD_LOGIC;
		 IBUS : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 A3SEL : OUT STD_LOGIC;
		 ROTSEL : OUT STD_LOGIC;
		 SHAMTSEL : OUT STD_LOGIC;
		 SRC2SEL : OUT STD_LOGIC;
		 REGWR : OUT STD_LOGIC;
		 MEMWR : OUT STD_LOGIC;
		 MEMRD : OUT STD_LOGIC;
		 A4SEL : OUT STD_LOGIC;
		 ALUSEL : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
		 CPSRWR : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
		 PCSEL : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
		 WD4SEL : OUT STD_LOGIC_VECTOR(1 DOWNTO 0)
	);
END COMPONENT;

COMPONENT decode
	PORT(A3SEL : IN STD_LOGIC;
		 ROTSEL : IN STD_LOGIC;
		 SHAMTSEL : IN STD_LOGIC;
		 SRC2SEL : IN STD_LOGIC;
		 REGWR : IN STD_LOGIC;
		 A4SEL : IN STD_LOGIC;
		 RST : IN STD_LOGIC;
		 CLK : IN STD_LOGIC;
		 IBUS : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 PC8 : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 WD4 : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 BRADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
		 RD3 : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
		 SRC1 : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
		 SRC2 : OUT STD_LOGIC_VECTOR(31 DOWNTO 0)
	);
END COMPONENT;

COMPONENT fetch
	PORT(PCWR : IN STD_LOGIC;
		 RST : IN STD_LOGIC;
		 CLK : IN STD_LOGIC;
		 PCD : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 IBUS : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
		 PC4 : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
		 PC8 : OUT STD_LOGIC_VECTOR(31 DOWNTO 0)
	);
END COMPONENT;

COMPONENT execute
	PORT(RST : IN STD_LOGIC;
		 CLK : IN STD_LOGIC;
		 ALUSEL : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
		 CPSRWR : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
		 SRC1 : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 SRC2 : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		 C : OUT STD_LOGIC;
		 V : OUT STD_LOGIC;
		 N : OUT STD_LOGIC;
		 Z : OUT STD_LOGIC;
		 F : OUT STD_LOGIC_VECTOR(31 DOWNTO 0)
	);
END COMPONENT;

SIGNAL	A3SEL_ALTERA_SYNTHESIZED :  STD_LOGIC;
SIGNAL	A4SEL_ALTERA_SYNTHESIZED :  STD_LOGIC;
SIGNAL	ALUF_ALTERA_SYNTHESIZED :  STD_LOGIC_VECTOR(31 DOWNTO 0);
SIGNAL	ALUSEL_ALTERA_SYNTHESIZED :  STD_LOGIC_VECTOR(3 DOWNTO 0);
SIGNAL	BRADDR_ALTERA_SYNTHESIZED :  STD_LOGIC_VECTOR(31 DOWNTO 0);
SIGNAL	C_ALTERA_SYNTHESIZED :  STD_LOGIC;
SIGNAL	CPSRWR_ALTERA_SYNTHESIZED :  STD_LOGIC_VECTOR(1 DOWNTO 0);
SIGNAL	IBUS_ALTERA_SYNTHESIZED :  STD_LOGIC_VECTOR(31 DOWNTO 0);
SIGNAL	N_ALTERA_SYNTHESIZED :  STD_LOGIC;
SIGNAL	PC_ALTERA_SYNTHESIZED4 :  STD_LOGIC_VECTOR(31 DOWNTO 0);
SIGNAL	PCSEL_ALTERA_SYNTHESIZED :  STD_LOGIC_VECTOR(1 DOWNTO 0);
SIGNAL	REGWR_ALTERA_SYNTHESIZED :  STD_LOGIC;
SIGNAL	ROTSEL_ALTERA_SYNTHESIZED :  STD_LOGIC;
SIGNAL	SHAMTSEL_ALTERA_SYNTHESIZED :  STD_LOGIC;
SIGNAL	SRC2SEL_ALTERA_SYNTHESIZED :  STD_LOGIC;
SIGNAL	SRC_ALTERA_SYNTHESIZED1 :  STD_LOGIC_VECTOR(31 DOWNTO 0);
SIGNAL	SRC_ALTERA_SYNTHESIZED2 :  STD_LOGIC_VECTOR(31 DOWNTO 0);
SIGNAL	V_ALTERA_SYNTHESIZED :  STD_LOGIC;
SIGNAL	WD4SEL_ALTERA_SYNTHESIZED :  STD_LOGIC_VECTOR(1 DOWNTO 0);
SIGNAL	WD_ALTERA_SYNTHESIZED4 :  STD_LOGIC_VECTOR(31 DOWNTO 0);
SIGNAL	Z_ALTERA_SYNTHESIZED :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_0 :  STD_LOGIC_VECTOR(0 TO 31);
SIGNAL	SYNTHESIZED_WIRE_1 :  STD_LOGIC_VECTOR(31 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_2 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_3 :  STD_LOGIC_VECTOR(31 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_4 :  STD_LOGIC_VECTOR(0 TO 31);


BEGIN 
SYNTHESIZED_WIRE_0 <= "00000000000000000000000000000000";
SYNTHESIZED_WIRE_2 <= '0';
SYNTHESIZED_WIRE_4 <= "00000000000000000000000000000000";



b2v_busmux1 : busmux4to1
PORT MAP(D0 => SYNTHESIZED_WIRE_0,
		 D1 => WD_ALTERA_SYNTHESIZED4,
		 D2 => BRADDR_ALTERA_SYNTHESIZED,
		 D3 => PC_ALTERA_SYNTHESIZED4,
		 S => PCSEL_ALTERA_SYNTHESIZED,
		 Y => SYNTHESIZED_WIRE_3);


b2v_control : control
PORT MAP(C => C_ALTERA_SYNTHESIZED,
		 V => V_ALTERA_SYNTHESIZED,
		 N => N_ALTERA_SYNTHESIZED,
		 Z => Z_ALTERA_SYNTHESIZED,
		 IBUS => IBUS_ALTERA_SYNTHESIZED,
		 A3SEL => A3SEL_ALTERA_SYNTHESIZED,
		 ROTSEL => ROTSEL_ALTERA_SYNTHESIZED,
		 SHAMTSEL => SHAMTSEL_ALTERA_SYNTHESIZED,
		 SRC2SEL => SRC2SEL_ALTERA_SYNTHESIZED,
		 REGWR => REGWR_ALTERA_SYNTHESIZED,
		 MEMWR => MEMWR,
		 MEMRD => MEMRD,
		 A4SEL => A4SEL_ALTERA_SYNTHESIZED,
		 ALUSEL => ALUSEL_ALTERA_SYNTHESIZED,
		 CPSRWR => CPSRWR_ALTERA_SYNTHESIZED,
		 PCSEL => PCSEL_ALTERA_SYNTHESIZED,
		 WD4SEL => WD4SEL_ALTERA_SYNTHESIZED);


b2v_decode : decode
PORT MAP(A3SEL => A3SEL_ALTERA_SYNTHESIZED,
		 ROTSEL => ROTSEL_ALTERA_SYNTHESIZED,
		 SHAMTSEL => SHAMTSEL_ALTERA_SYNTHESIZED,
		 SRC2SEL => SRC2SEL_ALTERA_SYNTHESIZED,
		 REGWR => REGWR_ALTERA_SYNTHESIZED,
		 A4SEL => A4SEL_ALTERA_SYNTHESIZED,
		 RST => RST,
		 CLK => CLK,
		 IBUS => IBUS_ALTERA_SYNTHESIZED,
		 PC8 => SYNTHESIZED_WIRE_1,
		 WD4 => WD_ALTERA_SYNTHESIZED4,
		 BRADDR => BRADDR_ALTERA_SYNTHESIZED,
		 RD3 => MEMDATAOUT,
		 SRC1 => SRC_ALTERA_SYNTHESIZED1,
		 SRC2 => SRC_ALTERA_SYNTHESIZED2);


b2v_inst1 : fetch
PORT MAP(PCWR => SYNTHESIZED_WIRE_2,
		 RST => RST,
		 CLK => CLK,
		 PCD => SYNTHESIZED_WIRE_3,
		 IBUS => IBUS_ALTERA_SYNTHESIZED,
		 PC4 => PC_ALTERA_SYNTHESIZED4,
		 PC8 => SYNTHESIZED_WIRE_1);



b2v_inst4 : execute
PORT MAP(RST => RST,
		 CLK => CLK,
		 ALUSEL => ALUSEL_ALTERA_SYNTHESIZED,
		 CPSRWR => CPSRWR_ALTERA_SYNTHESIZED,
		 SRC1 => SRC_ALTERA_SYNTHESIZED1,
		 SRC2 => SRC_ALTERA_SYNTHESIZED2,
		 C => C_ALTERA_SYNTHESIZED,
		 V => V_ALTERA_SYNTHESIZED,
		 N => N_ALTERA_SYNTHESIZED,
		 Z => Z_ALTERA_SYNTHESIZED,
		 F => ALUF_ALTERA_SYNTHESIZED);


b2v_inst6 : busmux4to1
PORT MAP(D0 => MEMDATAIN,
		 D1 => ALUF_ALTERA_SYNTHESIZED,
		 D2 => PC_ALTERA_SYNTHESIZED4,
		 D3 => SYNTHESIZED_WIRE_4,
		 S => WD4SEL_ALTERA_SYNTHESIZED,
		 Y => WD_ALTERA_SYNTHESIZED4);



A3SEL <= A3SEL_ALTERA_SYNTHESIZED;
ROTSEL <= ROTSEL_ALTERA_SYNTHESIZED;
SHAMTSEL <= SHAMTSEL_ALTERA_SYNTHESIZED;
SRC2SEL <= SRC2SEL_ALTERA_SYNTHESIZED;
REGWR <= REGWR_ALTERA_SYNTHESIZED;
A4SEL <= A4SEL_ALTERA_SYNTHESIZED;
C <= C_ALTERA_SYNTHESIZED;
V <= V_ALTERA_SYNTHESIZED;
N <= N_ALTERA_SYNTHESIZED;
Z <= Z_ALTERA_SYNTHESIZED;
ALUF <= ALUF_ALTERA_SYNTHESIZED;
ALUSEL <= ALUSEL_ALTERA_SYNTHESIZED;
BRADDR <= BRADDR_ALTERA_SYNTHESIZED;
CPSRWR <= CPSRWR_ALTERA_SYNTHESIZED;
IBUS <= IBUS_ALTERA_SYNTHESIZED;
MEMADDR <= ALUF_ALTERA_SYNTHESIZED;
PC4 <= PC_ALTERA_SYNTHESIZED4;
PCSEL <= PCSEL_ALTERA_SYNTHESIZED;
SRC1 <= SRC_ALTERA_SYNTHESIZED1;
SRC2 <= SRC_ALTERA_SYNTHESIZED2;
WD4 <= WD_ALTERA_SYNTHESIZED4;
WD4SEL <= WD4SEL_ALTERA_SYNTHESIZED;

END bdf_type;